import type { Metadata } from 'next'
import { Inter, Geist_Mono } from 'next/font/google'
import { CartProvider } from '@/context/CartContext'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import SessionProvider from '@/components/auth/SessionProvider'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider>
					<CartProvider>
						<Navbar />
						<main className="mx-auto px-4 py-8 min-h-screen">{children}</main>
						<Toaster richColors />
						<Footer />
					</CartProvider>
				</SessionProvider>
			</body>
		</html>
	)
}
